{% set name = "simpleitk" %}
{% set version = "2.0rc1" %}
{% set build_number = 0 %}

package:
  name: simpleitk
  version: "{{version}}"


source:
  git_url: https://github.com/SimpleITK/SimpleITK
  git_tag: v{version}}

build:
    number: "{{build_number}}"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake    >=3.11
    - swig     >=3,<4
    - ninja

  host:
    - python
    - setuptools
    - libtiff
    - libpng
    - jpeg
    - zlib

  run:
    - vs2015_runtime  # [win]
    - python
    - {{ pin_compatible('libtiff', max_pin='x.x') }}
    - {{ pin_compatible('libpng', max_pin='x.x') }}
    - {{ pin_compatible('jpeg', max_pin='x') }}
    - {{ pin_compatible('zlib', max_pin='x.x') }}


test:
  imports:
    - SimpleITK

about:
  home: http::/www.simpleitk.org
  license: Apache 2.0
  license_file: LICENSE
  summary: Simplified interface to the Insight Toolkit for image registration and segmentation

extra:
    recipe-maintainers:
      - blowekamp
      - zivy
