{% set name = "simpleitk" %}
{% set version = "2.2.1" %}
{% set build_number = 1 %}

package:
  name: simpleitk
  version: "{{version}}"


source:
  git_url: https://github.com/SimpleITK/SimpleITK
  git_tag: v{{version}}

build:
    number: "{{build_number}}"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake    >=3.16.3
    - swig     >=4,<5
    - ninja

  host:
    - python
    - setuptools
    - libtiff    # [not win]
    - libpng     # [not win]
    - jpeg       # [not win]
    - zlib       # [not win]
    - tbb-devel  # [not win]

  run:
    - vs2015_runtime  # [win]
    - python
    - {{ pin_compatible('libtiff', max_pin='x.x') }} # [not win]
    - {{ pin_compatible('libpng', max_pin='x.x') }}  # [not win]
    - {{ pin_compatible('jpeg', max_pin='x') }}      # [not win]
    - {{ pin_compatible('zlib', max_pin='x.x') }}    # [not win]
    - tbb # [not win]

test:
  imports:
    - SimpleITK

about:
  home: http::/www.simpleitk.org
  license: Apache 2.0
  license_file: LICENSE
  summary: Simplified interface to the Insight Toolkit for image registration and segmentation

extra:
    recipe-maintainers:
      - blowekamp
      - zivy
