{% set version = "1.1rc2" %}

package:
  name: simpleitk
  version: "{{version}}"

source:
  git_url: git://itk.org/SimpleITK.git
  git_tag:  v{{version}}

build:
    number: 0

requirements:
  build:
    - swig     >=3
    - cmake    >=3.3
    - setuptools
    - python
    - libtiff
    - libpng
    - jpeg
    - zlib

  run:
    - python
    - {{ pin_compatible('libtiff', max_pin='x.x') }}
    - {{ pin_compatible('libpng', max_pin='x.x') }}
    - {{ pin_compatible('jpeg', max_pin='x') }}
    - {{ pin_compatible('zlib', max_pin='x.x') }}


test:
  imports:
    - SimpleITK

about:
  home: http::/www.simpleitk.org
  license: Apache 2.0
  summary: Simplified interface to the Insight Toolkit for image registration and segmentation

extra:
    recipe-maintainers:
      - blowekamp
      - zivy
