{% set name = "simpleitk" %}
{% set version = "1.2.2" %}
{% set sha256 = "0af7387bd42bb535572b2c6c3b4ba0f9211e82a045d40ec2df507b73d5781231" %}
{% set build_number = 1 %}

package:
  name: simpleitk
  version: "{{version}}"


source:
  url: https://github.com/SimpleITK/SimpleITK/releases/download/v{{version}}/SimpleITK-{{version}}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Add-more-CMake-find-related-variables-including-fram.patch
    - 0002-Add-more-Superbuild-variables-to-support-find-root.patch

build:
    number: "{{build_number}}"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake    >=3.11
    - ninja

  host:
    - python
    - swig     >=3
    - setuptools
    - libtiff
    - libpng
    - jpeg
    - zlib

  run:
    - vs2015_runtime  # [win]
    - python
    - {{ pin_compatible('libtiff', max_pin='x.x') }}
    - {{ pin_compatible('libpng', max_pin='x.x') }}
    - {{ pin_compatible('jpeg', max_pin='x') }}
    - {{ pin_compatible('zlib', max_pin='x.x') }}


test:
  imports:
    - SimpleITK

about:
  home: http::/www.simpleitk.org
  license: Apache 2.0
  summary: Simplified interface to the Insight Toolkit for image registration and segmentation

extra:
    recipe-maintainers:
      - blowekamp
      - zivy
