variables:
  var.conda_version: 4.7.5
  var.conda_build_version: 3.18
jobs:
  - job: Windows
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    strategy:
      maxParallel: 2
      matrix:
        Python27:
          imageName: 'vs2017-win2016'
          var.python_version: 27
    pool:
      vmImage: $(imageName)

    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
        displayName: Checkout pull request HEAD
      - powershell: |
      - powershell: |

          Set-PSDebug -Trace 1

          $download_url="https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe"
          if ($env:VAR_ARCH -eq "x86")
            {
            $download_url="https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86.exe"
            }

          Write-Host "`nDownloading Miniconda Installer $download_url ...`n"
          (New-Object System.Net.WebClient).DownloadFile($download_url, "$pwd\Miniconda_Install.exe")

          Write-Host "Installing Miniconda...`n"
          $install_dir="C:\miniconda3"
          Start-Process Miniconda_Install.exe "/S /AddToPath=0 /D=$install_dir" -Wait

          Set-PSDebug -Trace 0

          Write-Host "##vso[task.prependpath]$install_dir\Scripts"
        displayName: "Installing Miniconda"
      - bash: |
          choco upgrade vcpython27 -fdv -y --debug
        condition:  lt(variables['var.python_version'], '33')
        displayName: "Installing Visual Studio for Python 2.7..."
      - powershell: |
          Set-PSDebug -Trace 1
          $batchcontent = @"
          ECHO ON
          SET vcpython=C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0
          DIR "%vcpython%"
          CALL "%vcpython%\vcvarsall.bat" %*
          "@
          $batchDir = "C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC"
          $batchPath = "$batchDir" + "\vcvarsall.bat"
          New-Item -Path $batchPath -ItemType "file" -Force
          Set-Content -Value $batchcontent -Path $batchPath
          Get-ChildItem -Path $batchDir
          Get-ChildItem -Path ($batchDir + '\..')
        condition:  lt(variables['var.python_version'], '33')
        displayName: Patch vs2008 (if needed)
      - bash: |
          source activate
          conda update -n base -c defaults conda -y
          conda create --yes --quiet --name bld
          conda activate bld
          conda install --yes --name bld conda-build=$VAR_CONDA_BUILD_VERSION
        displayName: "Updating conda-build..."
      - bash: |
          ls "${VS90COMNTOOLS}"
          source activate
          conda activate bld
          cd $(Build.SourcesDirectory)
          conda build --python "$VAR_PYTHON_VERSION" --output-folder channel recipe
        env: {
          VS90COMNTOOLS: "C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\bin",
        }
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/channel/'
          contents: '*/simpleitk*.tar.bz2'
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: false
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: AnacondaPackage

 
