variables:
  var.conda_version: 4.7.5
  var.conda_build_version: 3.18
jobs:
  - job: Windows
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 200
    strategy:
      maxParallel: 2
      matrix:
        Python39:
          imageName: 'vs2017-win2016'
          var.python_version: 39
        Python38:
          imageName: 'vs2017-win2016'
          var.python_version: 38
        Python37:
          imageName: 'vs2017-win2016'
          var.python_version: 37
        Python36:
          imageName: 'vs2017-win2016'
          var.python_version: 36

    pool:
      vmImage: $(imageName)

    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
        displayName: Checkout pull request HEAD
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to PATH
      - script: |
          # on Windows conda is a bat file that will exit it not "CALL"'d
          # https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#using-conda-in-windows-batch-script-exits-early
          call activate
          call conda update --yes conda
          call conda create --yes --quiet --name bld --no-default-packages
          call conda install --yes --name bld conda-build=$(var.conda_build_version)
        displayName: "Updating conda-build..."
      - script: |
          call activate bld
          cd $(Build.SourcesDirectory)
          call conda build --croot "$(Agent.BuildDirectory)" --no-build-id --python "$(var.python_version)" --output-folder channel recipe
        displayName: "Building..."
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/channel/'
          contents: '*/simpleitk*.tar.bz2'
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: false
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: AnacondaPackage

  - job: Linux

    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 200
    strategy:
      maxParallel: 2
      matrix:
        Python39:
          imageName: 'Ubuntu-16.04'
          var.python_version: 39
          var.arch: x64
        Python38:
          imageName: 'Ubuntu-16.04'
          var.python_version: 38
          var.arch: x64
        Python37:
          imageName: 'Ubuntu-16.04'
          var.python_version: 37
          var.arch: x64
        Python36:
          imageName: 'Ubuntu-16.04'
          var.python_version: 36
          var.arch: x64

    pool:
      vmImage: $(imageName)

    steps:
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
        displayName: Checkout pull request HEAD
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - bash: |
          which conda
          source activate
          conda update --yes conda
          conda create --yes --quiet --name bld --no-default-packages
          conda install --yes --name bld conda-build
        displayName: "Creating updated environment with conda-build..."
      - bash: |
          set -x
          source activate bld
          if [ ${VAR_ARCH} == "x86" ]; then
            LINUX32=$(which linux32)
            echo "LINUX32: ${LINUX32}"
          fi
          ${LINUX32} conda build --python "$VAR_PYTHON_VERSION" --output-folder channel recipe
        displayName: "Building conda package..."
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/channel/'
          contents: '*/simpleitk*.tar.bz2'
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: false
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: AnacondaPackage

  - job: MacOSX

    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 100
    strategy:
      maxParallel: 2
      matrix:
        Python39:
          imageName: 'macOS-10.14'
          MACOSX_DEPLOYMENT_TARGET: '10.9'
          var.python_version: 39
          var.arch: x64
        Python38:
          imageName: 'macOS-10.14'
          MACOSX_DEPLOYMENT_TARGET: '10.9'
          var.python_version: 38
          var.arch: x64
        Python37:
          imageName: 'macOS-10.14'
          MACOSX_DEPLOYMENT_TARGET: '10.9'
          var.python_version: 37
          var.arch: x64
        Python36:
          imageName: 'macOS-10.14'
          MACOSX_DEPLOYMENT_TARGET: '10.9'
          var.python_version: 36
          var.arch: x64

    pool:
      vmImage: $(imageName)

    steps:
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
        displayName: Checkout pull request HEAD
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: sudo chown -R $USER $CONDA
        displayName: Take ownership of conda installation

      - bash: |


          # see https://github.com/ContinuumIO/anaconda-issues/issues/9096
          # https://stackoverflow.com/questions/53637414/conda-build-r-package-fails-at-c-compiler-issue-on-macos-mojave
          $(Build.SourcesDirectory)/.azure-pipelines/support/osx_install_sdk.sh
          cat << EOF >> ${AGENT_BUILDDIRECTORY}/conda_build_config.yml
          CONDA_BUILD_SYSROOT:
             - $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk
          MACOSX_DEPLOYMENT_TARGET:
             - ${MACOSX_DEPLOYMENT_TARGET}
          EOF

          cat << EOF > ~/.condarc
          conda_build:
            config_file: ${AGENT_BUILDDIRECTORY}/conda_build_config.yml
          EOF


          source activate
          conda update --yes conda
          conda create --yes --quiet --name bld --no-default-packages
          conda install --yes --name bld conda-build

        displayName: "Creating updated environment with conda-build..."
      - bash: |

          export PYTHONUNBUFFERED=1
          set -x
          source activate bld
          conda build --python "$VAR_PYTHON_VERSION" --output-folder channel recipe
        displayName: "Building conda package..."
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/channel/'
          contents: '*/simpleitk*.tar.bz2'
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: false
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: AnacondaPackage
